// src/CodeBlock.tsx
import styles from "./CodeBlock.module.css";

import hljs from "highlight.js";

export function CodeBlock({
	caption = undefined,
	language,
	code,
}: {
	caption?: string,
	language: string,
	code: string,
}) {
	const highlightedCode = hljs.highlight(code, { language }).value;
	return <div className={styles.codeBlock}>
		{caption !== undefined && <div className={styles.caption}>{caption}</div>}
		<div className={styles.language}>{language}</div>
		<div className={`${styles.code} hljs`}>
			<pre><code className={styles.fontMonospace} dangerouslySetInnerHTML={{__html: highlightedCode }}></code></pre>
		</div>
	</div>;
}

// src/CodeBlock.vue
<script setup lang="ts">
import hljs from "highlight.js";
import "highlight.js/styles/atom-one-light.css";
interface Props {
	title?: string;
	language?: string;
	text: string;
}
const props = withDefaults(defineProps<Props>(), {
	title: undefined,
	language: "plaintext",
});
const highlighted = hljs.highlight(props.text, {
	language: props.language,
}).value;
</script>

<template>
	<div class="code-block hljs">
		<span v-if="title !== undefined" class="title">{{ title }}</span>
		<pre><code class="hljs" v-html="highlighted"></code></pre>
	</div>
</template>

<style scoped>
</style>
